name: privacygate
description: Cross-platform PrivacyGate mobile client for Android and iOS.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^7.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
